GET http://localhost:8000/process-url
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=R4AlFMAgDz0"
}

###
GET http://localhost:8000/api/recommend
Content-Type: application/json

{
  "days": 1,
  "places": [
    {
      "id": 1,
      "category": "음식점",
      "place_name": "이츠모라멘",
      "summary": "라멘 맛집",
      "latitude": 37.784818013,
      "longitude": 128.916060875
    },
    {
      "id": 2,
      "category": "음식점",
      "place_name": "초당찰떡",
      "summary": "찹쌀떡, 구운찰떡 판매, 네이버 예약 가능, 선물용으로 좋음",
      "latitude": 37.791413406,
      "longitude": 128.914894149
    }
  ]
}


###

GET http://localhost:8000/api/recommend
Content-Type: application/json

{
    "days": 3,
    "places": [
      {
        "id": 1,
        "category": "음식점",
        "place_name": "이츠모라멘",
        "summary": "라멘 맛집",
        "latitude" : 37.784818013,
        "longitude" : 128.916060875
      },
      {
        "id": 2,
        "category": "카페/디저트",
        "place_name": "초당찰떡",
        "summary": "찹쌀떡, 구운찰떡 판매, 네이버 예약 가능, 선물용으로 좋음",
        "latitude": 37.791413406,
        "longitude": 128.914894149
      },
      {
        "id": 3,
        "category": "음식점",
        "place_name": "형제막국수",
        "summary": "막국수와 수육 세트가 인기, 비빔막국수 추천",
        "latitude": 37.754977207,
        "longitude": 128.865507027
      },
      {
        "id": 4,
        "category": "음식점",
        "place_name": "여고시절 카레 떡볶이",
        "summary": "카레향이 나는 길거리 떡볶이 느낌, 떡과 어묵 개수 선택 가능",
        "latitude": 37.753026498,
        "longitude": 128.895780967
      },
      {
        "id": 5,
        "category": "음식점",
        "place_name": "두딩",
        "summary": "두부로 만든 푸딩 판매, 순두부와 푸딩 중간 질감",
        "latitude": 37.784818013,
        "longitude": 128.916060875
      },
      {
        "id": 6,
        "category": "카페/디저트",
        "place_name": "말차로",
        "summary": "말차라떼 맛집, 식후땡으로 추천",
        "latitude": 37.785756303,
        "longitude": 128.915247066
      },
      {
        "id": 7,
        "category": "카페/디저트",
        "place_name": "돌체테리아",
        "summary": "휘낭시에, 돌낭스크가 유명한 빵 맛집, 택배 주문 가능",
        "latitude": 37.767710525,
        "longitude": 128.876157729
      },
      {
        "id": 8,
        "category": "카페/디저트",
        "place_name": "카페삐삐",
        "summary": "모던하고 컬러풀한 인테리어, 브런치 메뉴, 혼자 여행객에게 추천",
        "latitude": 37.757851691,
        "longitude": 128.893473419
      },
      {
        "id": 9,
        "category": "관광지",
        "place_name": "강문해변",
        "summary": "주차장에서 해변 접근성 좋음, 피크닉 추천",
        "latitude": 37.753026498,
        "longitude": 128.895780967
      },
      {
        "id": 10,
        "category": "쇼핑",
        "place_name": "슬로우슬로우담담",
        "summary": "수제 도자기 소품 판매, 마음의 조각들이라는 도자기 조각 판매",
        "latitude": 37.757124133,
        "longitude": 128.893408744
      },
      {
        "id": 11,
        "category": "쇼핑",
        "place_name": "르봉마젤",
        "summary": "프랑스 파리 감성의 식기 및 소품 판매, 1,2층은 소품샵, 탐사층은 카페",
        "latitude": 37.756962769,
        "longitude": 128.893373650
      },
      {
        "id": 12,
        "category": "쇼핑",
        "place_name": "사유의 공간",
        "summary": "앤틱하고 빈티지한 인테리어 소품 판매",
        "latitude": 37.758360267,
        "longitude": 128.891961145
      },
      {
        "id": 13,
        "category": "쇼핑",
        "place_name": "비비플로",
        "summary": "카페 겸 소품샵, 자체 제작 상품과 아카이빙 브랜드 상품 판매, 인스타그램 택배 주문 가능",
        "latitude": 37.767466535,
        "longitude": 128.913709633
      },
      {
        "id": 14,
        "category": "활동/체험",
        "place_name": "히든서프",
        "summary": "서핑 강습 및 숙박 가능, 픽업 서비스 제공, 파티 등 새로운 사람들과의 만남 기회 제공",
        "latitude": 37.841710593,
        "longitude": 128.874631059
      }
    ]
}
