### Test /process-url endpoint
POST http://localhost:8000/process-url HTTP/1.1
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=https://www.youtube.com/watch?v=R4AlFMAgDz0"
}

### Test /api/recommend endpoint
POST http://localhost:8000/api/recommend HTTP/1.1
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=your_video_id"
}